import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="glass-strong rounded-2xl p-8 max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold text-viking-snow font-[family-name:var(--font-display)] text-center">
        Terms & Conditions
      </h1>
      <p className="mt-2 text-xs text-viking-steel text-center">Last updated: March 31, 2026</p>

      <div className="mt-8 space-y-6 text-sm text-viking-steel leading-relaxed">
        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">1. Acceptance of Terms</h2>
          <p>
            By creating an account and using Valhalla (&quot;the Service&quot;), you agree to be bound by these
            Terms & Conditions. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">2. Service Description</h2>
          <p>
            Valhalla provides AI-powered predictions for sports memorabilia investments using machine learning
            models. Predictions are generated by an XGBoost model trained on historical deal data and are intended
            for informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">3. No Financial Advice</h2>
          <p>
            The predictions and analysis provided by Valhalla do not constitute financial, investment, or
            trading advice. You should not make any investment decision based solely on information provided by
            the Service. Always conduct your own research and consult with a qualified financial advisor.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">4. Account Responsibility</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials. You agree to
            provide accurate and complete information during registration and to keep your account information
            up to date.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">5. Data Collection & Privacy</h2>
          <p>
            We collect personal information (name, email, phone) during registration and prediction data during
            use. Your data is stored securely and will not be sold to third parties. We use your data solely to
            provide and improve the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">6. Limitation of Liability</h2>
          <p>
            Valhalla and its operators shall not be liable for any direct, indirect, incidental, or
            consequential damages arising from your use of the Service or reliance on its predictions.
            The Service is provided &quot;as is&quot; without warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-viking-mist mb-2">7. Modifications</h2>
          <p>
            We reserve the right to modify these Terms at any time. Continued use of the Service after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>
      </div>

      <div className="mt-8 text-center">
        <Link
          href="/signup"
          className="inline-block rounded-xl border border-viking-steel/20 px-6 py-3 text-sm font-semibold text-viking-snow transition-all hover:border-viking-steel/40 hover:bg-viking-snow/5"
        >
          Back to Sign Up
        </Link>
      </div>
    </div>
  );
}
