export default function Footer() {
  return (
    <footer className="relative border-t border-viking-iron/30">
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-viking-gold/30 to-transparent" />
      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2 font-[family-name:var(--font-display)] font-bold text-lg">
            <span className="text-viking-gold">VIKING</span>
            <span className="text-viking-snow">SPORTS</span>
          </div>

          <p className="text-xs text-viking-steel/60 max-w-md text-center md:text-right leading-relaxed">
            Predictions are generated by a machine learning model trained on
            historical data and should not be considered financial advice.
            Past performance does not guarantee future results.
          </p>
        </div>

        <div className="mt-8 pt-6 border-t border-viking-iron/20 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-viking-steel/40">
            &copy; {new Date().getFullYear()} Viking Sports. All rights
            reserved.
          </p>
          <p className="text-xs text-viking-steel/40">
            Powered by XGBoost &middot; Built with Next.js
          </p>
        </div>
      </div>
    </footer>
  );
}
